# Generated by Django 4.0.1 on 2022-03-11 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('biData', models.CharField(max_length=50, null=True)),
                ('sqlData', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('text', models.CharField(max_length=50, null=True)),
                ('fileReport', models.FileField(null=True, upload_to='reportFiles')),
                ('imageReport', models.ImageField(null=True, upload_to='reportImage')),
                ('viewsReport', models.IntegerField(null=True)),
                ('uses', models.IntegerField(null=True)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.categories')),
                ('fileType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.reporttype')),
                ('levels', models.ManyToManyField(to='users.Levels')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('nationalId', models.CharField(blank=True, max_length=30, null=True)),
                ('deviceId', models.CharField(blank=True, max_length=500)),
                ('levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.levels')),
                ('singleLevels', models.ManyToManyField(to='users.Report')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
