# Generated by Django 4.0.1 on 2022-03-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='report',
            name='fileType',
        ),
        migrations.RemoveField(
            model_name='report',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='singleLevels',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Levels',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
